# This is a basic workflow to help you get started with Actions

name: CI First Push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Checkout 
        uses: actions/checkout@v5
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Display message
        run: echo "This is the first Github action project"

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          ls 
          cat .github/workflows/README.md

      - name: Install cowsay
        run: sudo apt-get install cowsay -y

      - name: Generate ASCII artwork
        run: cowsay -f dragon "Run cowsay" >> dragon.txt
      
      - name: Check for file 
        run: grep -i "dragon" dragon.txt

      # Runs a set of commands using the runners shell
    
