# This is a basic workflow to help you get started with Actions

name: CI First Push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Checkout 
        uses: actions/checkout@v5
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Display message
        run: echo "This is the first Github action project"

      # Runs a single command using the runners shell
      - name: Execute shell script
        run: |
          chmod +x .github/workflows/shell-script.sh
          .github/workflows/shell-script.sh
  
  Test_job:
      runs-on: ubuntu-latest
      steps:
    # The type of runner that the job will run on
      
      - name: Check if the file is created 
        run: grep -i "dragon" dragon.txt || echo "No match found...continuing"

  Deploy_job:

      runs-on: ubuntu-latest
      steps:

      - name: Execute shell script
        run: |
          chmod +x .github/workflows/shell-script.sh
          .github/workflows/shell-script.sh


          
      # Runs a set of commands using the runners shell
    
